import { readdirSync, statSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import type { AnchorTargetConfig } from "../config/AnchorConfig.js";

export interface BaselineSection {
	path: string;
	content: string;
}

export interface BaselineGenerationInput {
	sourcePath: string;
	targets: AnchorTargetConfig[];
}

export class SectionGenerator {
	generate(input: BaselineGenerationInput): BaselineSection[] {
		const sourceRoot = resolve(input.sourcePath);
		const fileList = listFiles(sourceRoot).slice(0, 200);

		const overviewLines: string[] = [];
		overviewLines.push("# Baseline Overview");
		overviewLines.push("");
		overviewLines.push("This baseline corpus was generated by Anchor.");
		overviewLines.push("");
		overviewLines.push(`- Source path: ${sourceRoot}`);
		overviewLines.push(`- Generated at: ${new Date().toISOString()}`);
		overviewLines.push(`- Files sampled: ${fileList.length}`);
		overviewLines.push("");
		overviewLines.push("## Detected targets");
		overviewLines.push("");

		for (const target of input.targets) {
			overviewLines.push(`- ${target.name}${target.description ? `: ${target.description}` : ""}`);
		}

		const inventoryLines: string[] = [];
		inventoryLines.push("# File Inventory");
		inventoryLines.push("");
		inventoryLines.push("Sampled files detected during baseline generation:");
		inventoryLines.push("");

		for (const filePath of fileList) {
			inventoryLines.push(`- ${filePath}`);
		}

		const targetsLines: string[] = [];
		targetsLines.push("# Targets");
		targetsLines.push("");

		for (const target of input.targets) {
			targetsLines.push(`## ${target.name}`);
			targetsLines.push("");
			if (target.description) {
				targetsLines.push(target.description);
				targetsLines.push("");
			}
			targetsLines.push(`- fileGlobs: ${target.fileGlobs.join(", ")}`);
			if (target.excludeGlobs && target.excludeGlobs.length > 0) {
				targetsLines.push(`- excludeGlobs: ${target.excludeGlobs.join(", ")}`);
			}
			if (target.minSeverity) {
				targetsLines.push(`- minSeverity: ${target.minSeverity}`);
			}
			targetsLines.push("");
		}

		return [
			{ path: "overview.md", content: `${overviewLines.join("\n")}\n` },
			{ path: "inventory/files.md", content: `${inventoryLines.join("\n")}\n` },
			{ path: "targets.md", content: `${targetsLines.join("\n")}\n` },
		];
	}
}

function listFiles(root: string): string[] {
	const out: string[] = [];
	walk(root, root, out);
	return out.sort();
}

function walk(root: string, current: string, out: string[]): void {
	for (const entry of readdirSync(current)) {
		if (entry === ".git" || entry === "node_modules") {
			continue;
		}

		const absolute = join(current, entry);
		const stat = statSync(absolute);
		if (stat.isDirectory()) {
			walk(root, absolute, out);
			continue;
		}

		out.push(relative(root, absolute).replace(/\\/g, "/"));
	}
}
